messages:
  prefix: '&7Охранник Балто &8>> &f'
  noperm: '{prefix}&cУ Вас недостаточно прав!'
  notinlist: '{prefix}&cВы не находитесь в списке разрешённых пользователей для захода на данный режим!'
  accepted: '{prefix}&aДобро пожаловать на режим {game}&a!'
  intest: '{prefix}&cВНИМАНИЕ!&f В данный момент режим находится в тестовом режиме! Это значит, что в нём могут быть различные виды багов. Сообщайте о них в тикеты: &bhttps://dreamtime.su/tickets'
  kickmsg: '&9&lDREAM&b&lTIME\n\n&cВы не можете подключиться к серверу!\n&cПричина:\n&7{reason}\n\n&6https://vk.com/mc_dreamtime &c|| &6https://dreamtime.su/'
  help:
  - '{prefix}&aВсе команды плагина:'
  - '&a> &7/dtwl help - Эти сообщения'
  - '&a> &7/dtwl player add <режим> <игрок> - добавить игрока в список разрешённых'
  - '&a> &7/dtwl player remove <режим> <игрок> - убрать игрока из списка'
  - '&a> &7/dtwl server perm <название> - переключить вход по перму'
  - '&a> &7/dtwl server enabled <название> - переключить режим на сервере'
  - '&a> &7/dtwl server test <название> - переключить режим теста на сервере'
  - '&a> &7/dtwl server reason <название> <причина> - изменить причину кика'
  - '&a> &7/dtwl server info <название> - получить информацию о сервере'
  - '&a> &7/dtwl server list <название> - посмотреть игроков, находящихся в белом списке '
  servernotfound: '{prefix}&cРежим не найден!'

#Сервера
#Все сервера, которые не указаны, можно добавить через команду /dtwl server add <название>
servers:
  #_bungee_ - глобальный, при соединении к бамже
  _bungee_:
    #Включен ли вайтлист
    enable: true
    #Если true, то право на вход - dtwl.join._bungee_
    withperm: false
    #Список тех, кто может зайти, когда withperm стоит на false
    list:
    - 'yiaaanni'
    - 'thelightbringer'
    - 'sonechkanuasha'
    - 'pro100lolyt'
    - 'stevegrkek'
    - 'noteyourdope'
    - 'glimmerkeepen'
    #Кикать ли с сервера
    kick: true
    #Причина кика (пишется в сообщении kickmsg {reason})
    kickreason: 'Закрытый Бета Тест'
    #В тесте или нет
    intest: true
